services:
  backend:
    image: magx26/ismasocial-back:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ismasocial
      - PORT=5000
      - JWT_SECRET=a3f5b78d5e9c46b38d5a6d087c67d9f0fe0c9a84dc576b2e074c25ec4a5df29b
    depends_on:
      - mongo

  client:
    image: magx26/ismasocial-front:latest
    ports:
      - "3001:3000" 
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "3002:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:

